name: /data/amb10399/envs/fno
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bottleneck=1.3.7=py312ha883a20_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py312h6a678d5_8
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py312h06a4308_0
  - cffi=1.16.0=py312h5eee18b_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py312hdb19cb5_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.1=py312h30efb56_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h59595ed_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py312h06a4308_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonttools=4.51.0=py312h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2024.3.1=py312h06a4308_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h5py=3.9.0=py312h34c39bb_0
  - hdf5=1.12.1=h2b7332f_3
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.22.2=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=py312h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312h7900ff3_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py312h6a678d5_0
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h55db66e_0
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.5.147=0
  - libcurl=8.5.0=h251f7ec_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h7f8727e_1
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=13.2.0=h77fa898_6
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=13.2.0=h77fa898_6
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnsl=2.0.1=hd590300_0
  - libnvjpeg=11.9.0.86=0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.45.3=h2797004_0
  - libssh2=1.10.0=hdbd6064_3
  - libstdcxx-ng=13.2.0=hc0a3c3a_6
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hfdd30dd_2
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py312h5eee18b_0
  - matplotlib=3.8.4=py312h06a4308_0
  - matplotlib-base=3.8.4=py312h526ad5a_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.8=py312h5eee18b_0
  - mkl_random=1.2.4=py312hdb19cb5_0
  - mpmath=1.3.0=py312h06a4308_0
  - mysql=5.7.20=hf484d3e_1001
  - ncurses=6.4.20240210=h59595ed_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py312h06a4308_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numexpr=2.8.7=py312hf827012_0
  - numpy=1.26.4=py312hc5e2394_0
  - numpy-base=1.26.4=py312h0da6c21_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.3.0=hd590300_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.2.1=py312h526ad5a_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.3.0=py312h5eee18b_0
  - pip=24.0=pyhd8ed1ab_0
  - platformdirs=4.2.1=pyhd8ed1ab_0
  - ply=3.11=py312h06a4308_1
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py312h98912ed_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyparsing=3.0.9=py312h06a4308_0
  - pyqt=5.15.10=py312h6a678d5_0
  - pyqt5-sip=12.13.0=py312h5eee18b_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.3=hab00c5b_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.12=4_cp312
  - pytorch=2.2.2=py3.12_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.1=py312h5eee18b_0
  - pyzmq=26.0.2=py312h8fd38d8_0
  - qt-main=5.15.2=h53bd1ea_10
  - readline=8.2=h8228510_1
  - requests=2.31.0=py312h06a4308_1
  - scipy=1.13.0=py312hc5e2394_0
  - setuptools=69.5.1=pyhd8ed1ab_0
  - sip=6.7.12=py312h6a678d5_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h2c6b66d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=py312h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.2.2=py312_cu118
  - torchvision=0.17.2=py312_cu118
  - tornado=6.4=py312h98912ed_0
  - tqdm=4.66.2=py312he106c6f_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.9.0=py312h06a4308_1
  - tzdata=2024a=h0c530f3_0
  - unicodedata2=15.1.0=py312h5eee18b_0
  - urllib3=2.1.0=py312h06a4308_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hc292b87_2
  - pip:
      - boltons==24.0.0
      - docopt==0.6.2
      - environs==11.0.0
      - jenn==1.0.3
      - joblib==1.4.2
      - marshmallow==3.21.2
      - msgpack==1.0.8
      - orjson==3.10.3
      - pydoe==0.3.8
      - pydoe3==1.0.2
      - pyfiglet==1.0.2
      - python-dotenv==1.0.1
      - scikit-learn==1.4.2
      - smt==2.5.1
      - sourcedefender==11.0.20
      - tgcrypto==1.2.5
      - threadpoolctl==3.5.0
      - torchdiffeq==0.2.3
      - typing-extensions==4.11.0
